package gui;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import domein.SessieKalenderController;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;
import javafx.scene.control.DatePicker;

public class SessieKalenderAanmakenSchermController extends AnchorPane{
	@FXML
	private DatePicker inputStartDatum;
	@FXML
	private DatePicker inputEindDatum;
	@FXML
	private Button btnVoegSessieKalenderToe;
	@FXML
	private Label lblErrorVoegSessieKalenderToe;
	

	private SessieKalenderController dc;
	
	
	public SessieKalenderAanmakenSchermController(SessieKalenderController dc) {
		try 
		{
			this.dc = dc;
			System.out.println("Laad nieuw voeg sessie kalender toe scherm");
			FXMLLoader loader = new FXMLLoader();
			loader.setLocation(getClass().getResource("SessieKalenderAanmaken.fxml"));
			loader.setRoot(this);
			loader.setController(this);
			loader.load();
			
		} catch (Exception e) {
			System.err.println(e.getMessage());
		}
	}
	
	// Event Listener on Button[#btnVoegSessieKalenderToe].onAction
	@FXML
	public void voegSessieKalenderToe(ActionEvent event) {
		// TODO Autogenerated
	}
}
